# Server configuration
spring.application.name=microservice-diabetes-risk
server.port=8084
server.error.whitelabel.enabled=false

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

frontend.patient-url=http://localhost:8081
frontend.note-url=http://localhost:8083