# Environment variables import
spring.config.import=optional:file:.env[.properties]

# Server configuration
spring.application.name=microservice-patient
server.port=8081

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Medilabo_Solutions
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}
spring.jpa.show-sql=true