# Server configuration
spring.application.name=microservice-frontend
server.port=8082
server.error.whitelabel.enabled=false

# Eureka Server URL
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

frontend.patient-url=http://patient-service:8081
frontend.note-url=http://note-service:8083
frontend.diabetes-url=http://diabetes-risk-service:8084