# Environment variables import
spring.config.import=optional:file:.env[.properties]

# Server configuration
spring.application.name=microservice-gateway
server.port=8080

# Eureka discovery configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Eureka Debug Level
logging.level.org.springframework.cloud.gateway=DEBUG

# Datasource configuration
spring.r2dbc.url=r2dbc:mysql://localhost:3306/Medilabo_Solutions
spring.r2dbc.username=${MYSQL_DB_USERNAME}
spring.r2dbc.password=${MYSQL_DB_PASSWORD}
spring.sql.init.mode=always
spring.r2dbc.show-sql=true